services:

  redis-storage:
    image: redis
    volumes:
      - ./redis:/data

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME:-books_database}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-password}
    volumes:
      - ./db/mongo:/data/db

  mongo_express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME:-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD:-password}
    depends_on:
      - mongodb

  ndse_library:
    build: ./library
    environment:
      - PORT=80
      - COUNTER_URL=http://ndse_counter
      - DB_URL=mongodb://${DB_USERNAME:-root}:${DB_PASSWORD:-password}@mongodb:27017/
    ports:
      - 3002:80
    depends_on:
      - ndse_counter

  ndse_counter:
    build: ./counter
    environment:
      - PORT=80
      - REDIS_URL=redis://redis-storage
    ports:
      - 3003:80
    depends_on:
      - redis-storage

