services:

  redis-storage:
    image: redis
    volumes:
      - ./redis:/data

  ndse_library:
    build: ./library
    environment:
      - PORT=3002
    ports:
      - 3002:3002
    depends_on:
      - ndse_counter

  ndse_counter:
    build: ./counter
    environment:
      - PORT=3003
      - REDIS_URL=redis://redis-storage
    ports:
      - 3003:3003
    depends_on:
      - redis-storage

