services:

  redis-storage:
    image: redis
    volumes:
      - ./redis:/data

  ndse_library:
    image: node:18.16
    volumes:
      - ./library/app:/app
    working_dir: /app
    environment:
      - PORT=3002
    ports:
      - 3002:3002
    command: npm run dev
    depends_on:
      - ndse_counter

  ndse_counter:
    image: node:18.16
    volumes:
      - ./counter/app:/app
    working_dir: /app
    environment:
      - PORT=3003
      - REDIS_URL=redis://redis-storage
    ports:
      - 3003:3003
    command: npm run dev
    depends_on:
      - redis-storage

